image: julia:1.11.7

stages:
  # - test
  - docs

variables:
  JULIA_NUM_THREADS: "auto"

# test:
#   stage: test
#   tags:
#     - docker
#   script:
#     - julia --project -e 'using Pkg; Pkg.instantiate()'
#     - julia --project -e 'using Pkg; Pkg.test("HyQMOM"; coverage=true)'
#   cache:
#     paths:
#       - .julia/

pages:
  stage: docs
  tags:
    - docker
  script:
    - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
    - julia --project=docs --color=yes docs/make.jl
    - mv docs/build public
  artifacts:
    paths:
      - public
  only:
    - main
  cache:
    paths:
      - .julia/